version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rede_social_db_example
    restart: always
    environment:
      # WARNING: Fill in with the same data as your .env file
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: